### ISSUE TITLE
Allow inserting point processes defined by MOD files

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#10]
The basic functionality is critical (e.g. to handle a MOD-file synapse mechanism) but it requires something more general than the `IClamp` class in the using-python branch which is for that MOD file mechanism only. This can probably be done without creating a fully dynamic interface though using some generic PointProcess class.

**Comment by ramcdougal** [comment]
This probably already works, but it hasn't been tested.

**Comment by edovanveen** [comment]
See https://nrn.readthedocs.io/en/8.2.2/guide/faq.html#how-do-i-compile-mod-files

**Comment by ramcdougal** [comment]
Example mod file:

https://senselab.med.yale.edu/modeldb/getModelFile?model=87284&AttrID=23&s=yes&file=/%2fCA1_abeta%2fh.mod

Compile with `nrnivmodl`, use `nrn_load_dll` with a path to load the generated dll file.

**Comment by edovanveen** [comment]
I tried this (see PR #59) and it worked out of the box!
