### ISSUE TITLE
FInitializeHandler

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#11]
Initialization is a critical aspect of defining a simulation.

We must allow a way for MATLAB functions to control initialization. In Python and HOC this is done using the [`FInitializeHandler`](https://nrn.readthedocs.io/en/latest/python/simctrl/programmatic.html#finitializehandler) class which registers callbacks at four separate stages of initialization.

**Comment by ramcdougal** [comment]
In order to do this, it might help if there was a good way of calling MATLAB from Python/HOC (see issue #9) but not strictly required.

**Comment by ramcdougal** [comment]
This probably requires changes to NEURON.

`FInitializeHandler` is defined in [src/nrniv/finithnd](https://github.com/neuronsimulator/nrn/blob/master/src/nrniv/finithnd.cpp). The key detail is that we need to be able to create a `HocCommand` that isn't for just HOC or Python.

**Comment by ramcdougal** [comment]
For context: `FInitializeHandler` objects are used to define elaborate initialization rules (as opposed to initializing to a uniform membrane potential everywhere). Certain aspects of initialization have to happen in certain orders, so it is not the same as doing a regular `finitialize` followed by changing the values.

A way to make this work: we can define a paring between a name and a C function pointer in the NEURON stack machine. This would add entries into the NEURON name space, but it would be mostly fine if they had some elaborate autogenerated name, say `neuron_toolbox_5243_64AE_5424` where the last bit is some kind of UUID.

Once they're known to the stack machine, they can be called by e.g. `FInitializeHandler` by `hoc_pushstr` a string that is the name and open and closed parentheses. 

For a working example, see https://github.com/mcdougallab/neuron-c-api-demos/blob/main/function-callbacks-nrn9/function-callbacks.cpp

The key parts are:

```C++
void new_finitialize_rule(void) {
    Symbol* const v = hoc_lookup("v");
    // set my_section(0.0.833333).v = 47
    *nrn_rangepointer(my_section, v, 0.833333) = 47;
    hoc_ret();
    hoc_pushx(0);
}

...

    // register the function new_finitialize_rule with NEURON
    char* my_generated_name_char = const_cast<char*>(my_generated_name.c_str());
    sym = hoc_install(my_generated_name_char, FUNCTION_TYPE, 0, hoc_top_level_symlist);
    sym->u.u_proc->defn.pf = new_finitialize_rule;
    sym->u.u_proc->nauto = 0;  // total number of local variables; always 0 for C++ function
    sym->u.u_proc->nobjauto = 0;

...

    // in Python (calling a HOC function): fih = h.FInitializeHandler("new_finitialize_rule()")
    // there is surely a better way to get the necessary char**
    string command = my_generated_name;
    command += "()";
    char* command_c = const_cast<char*>(command.c_str());
    hoc_pushstr(&command_c);
    auto ps = hoc_newobj1(hoc_lookup("FInitializeHandler"), 1);  // 1 for 1 argument
```

This is functionally very simple, but what it does do is that during the call `finitialize(-65);` it sets the membrane potential to -65 mV everywhere except on `my_section(0.833333)` where it is equal to 47.

**Comment by edovanveen** [comment]
To do:

* deal with arguments using `hoc_gargstr()`
* make a matlab wrapper for HOC's `FInitializeHandler`
