### ISSUE TITLE
Live Editor example

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#13]
Need one or more examples like the below, but that show off the capabilities of the supported parts of NEURON (PlotShapes, RangeVarPlots, in addition to time series).. maybe a network with a raster plot, probably a cleaner form.

![image](https://user-images.githubusercontent.com/6668090/126332511-4dfc61af-963e-413a-bb5a-a9fef323a528.png)

**Comment by ramcdougal** [comment]
#23 has an example

**Comment by vijayiyer05** [comment]
Some ideas for fleshing this out:

* Incorporate the new plot types (#3 , #6 )
* Add a live control to add some user-interactivity

**Comment by edovanveen** [comment]
@ramcdougal The current `example_interactive.mlx` on the main branch already has an action potential plot with live controls. Perhaps it would be nice to add a nice PlotShape cell plot as well, can we get an example cell for a nice PlotShape cell plot?

**Comment by edovanveen** [comment]
- [x] finitializehandler example script
- [ ] Add the `c91662.ses` PlotShape example
