### ISSUE TITLE
Prevent Matlab hard crash on Neuron internal error

### ISSUE THREAD

**Issue by AljenU** [mcdougallab/matlabneuroninterface#19]
There are multiple possible causes for a Neuron internal error. In some cases, it is possible to prevent an additional Matlab hard crash:

- 'Old' Neuron objects still on the stack when initializing a new simulation. -> Fixable by having the correct code in matlabneuroninterface to check this / prevent this from happening.
- Passing the wrong number of arguments for a function call. -> Due to dynamic function calling, cannot prevent the user from doing this? Neuron 9 will at least have a mechanism to catch errors due to this kind of problems. The matlabneuroninterface will need to have the capability to reset to a correct state when it happens.

**Comment by AljenU** [comment]
From https://github.com/edovanveen/matlabneuroninterface/pull/3#discussion_r1036944489
"reset_sections is missing from this example
Also since we nearly always want it, should reset_sections be added in the constructor of Neuron?
Could have option, through input argument to constructor, to NOT do it, but default is to reset_sections?"

**Comment by ramcdougal** [comment]
I don't think that we'd want creating a NEURON connection to destroy an existing NEURON model... in my mind the class should be a defacto singleton since all instances share the same model.

**Comment by AljenU** [comment]
To determine which neuron version the user is using, can call "nrniv --version"

nrniv --version
INFO : Using neuron-nightly Package (Developer Version)
NEURON -- VERSION 9.0.dev-1329-g4b26ff135 HEAD (4b26ff135) 2023-03-30

nrniv --version
NEURON -- VERSION 8.0.2+ HEAD (f0ca745+) 2022-02-02

**Comment by AljenU** [comment]
This issue is related to #15

**Comment by edovanveen** [comment]
In the latest version of neuron 9, it looks like some neuron types have changed (see https://github.com/mcdougallab/matlabneuroninterface/commit/1cc73bb177945bd4cd35a4c6998cccf6a7791bc6).

**Comment by edovanveen** [comment]
New crash (after renaming `Object.delete()`): running either `example_netcon` or `example_temptest` twice results in a crash. Running `example_patternstim` twice and then `example_savestate` also results in a crash.

**Comment by ramcdougal** [comment]
I think we can re-close this now after today's changes to #47? @edovanveen

**Comment by edovanveen** [comment]
Yes, the only known remaining crash on Windows is has been moved to issue #70
