### ISSUE TITLE
Vectors should be plottable directly

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#2]
e.g. if we've done

```matlab
t = n.Vector().record(n.t_ptr)
v = n.Vector().record(soma.seg(0.5).v_ptr)
```
then we would like to be able to do
```
plot(t, v)
```
without any explicit conversions (e.g. at this writing, the using-python branch requires `plot(t.to_matlab(), v.to_matlab())`)

**Comment by vijayiyer05** [comment]
This could potentially be included as a task "sub-issue" within an umbrella issue aiming to create **an object-oriented "middle layer" between the user and the clib package**. For instance, e.g. the creation of MATLAB classes that represent NEURON vectors for purposes like plotting. 

@ramcdougal , this is mostly a note to self at the moment to help me map my thinking to yours. But if a path is clear to you right away, you may want to try out the GitHub [tasklist beta](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists) to cluster your issues into higher-level umbrella issues.

**Comment by ramcdougal** [comment]
Out of curiosity, is there an existing way to make a MATLAB class be something you can send to `plot`?

E.g.

    plot(t, myobj)

**Comment by vijayiyer05** [comment]
MATLAB does include a number of builtin mixin classes, but there is not a "plottable" mixin to my knowledge.

What I guess makes sense in this case would be for the  `+neuron` namespace package to define its own `plot` function. Then the semantics would be 

`>>neuron.plot(t,myobj)`

**Comment by ramcdougal** [comment]
Okay, so this could be as simple as a thin-wrapper for the regular `plot` function that checks all the arguments to see if any of them are `Vector` objects, and if so calls `.to_matlab()` on them (or whatever) to get a MATLAB array before passing the arguments to `plot`.

Also, as part of my MATLAB-wishlist, it would be great if MATLAB supported some sort of abstract array class that user-defined types could inherit from and that would work (although, presumably slower) wherever arrays were supported. That means child classes would work with not just `plot` but with tons of other functions simply by supporting a single interface.

**Comment by ramcdougal** [comment]
In pure MATLAB, we can have Vector classes have a `toDouble` method... this is the approach taken in the pull request.

**Comment by vijayiyer05** [comment]
Since primitive class names are already built-in functions, it can make sense to have such conversion methods simply be the primitive class name. In other words: just `double`. Then you can use `double(myVec)` just like you could use `double` for casting any other MATLAB type.

**Comment by ramcdougal** [comment]
I thought the `double` function implicitly called a class's `toDouble` method?

See, e.g. http://matlab.izmiran.ru/help/techdoc/matlab_external/ch7_ja37.html

**Comment by vijayiyer05** [comment]
Hmm, that seems to be some undocumented MATLAB and I honestly can't say how current it is. 

Not a big deal at this stage either way.
