### ISSUE TITLE
Add (automated) tests for the interface

### ISSUE THREAD

**Issue by AljenU** [mcdougallab/matlabneuroninterface#30]
No tests yet. 
Add e.g. automated tests around the livescript examples.

**Comment by edovanveen** [comment]
To run automated tests we probably need the Linux version to work properly. See: https://github.com/matlab-actions/overview/blob/main/README.md; this works on a Linux VM.

**Comment by AljenU** [comment]
There is some, as yet undocumented, Windows support: https://github.com/matlab-actions/setup-matlab/issues/18#issuecomment-1006990188
