### ISSUE TITLE
Use full paths, especially in setup and utils.build_interface

### ISSUE THREAD

**Issue by AljenU** [mcdougallab/matlabneuroninterface#31]
Currently, the code uses paths relative to the source root directory. However, it is very possible that the user has a different current-directory when calling functions from this code.

For use outside of the setup function (in build_interface), can have a util.getRootSourceDir() function, to get the path to append to relative paths, using fullfilename.
However, during setup, our code is not yet on the path, so there will have to use a local variable.
In both cases, will use mfilename('fullpath'), with the correct amount of fileparts() calls around it, to get the root source directory path.

E.g. in setup, instead of `addpath neuron`, have
```
rootSourceDir = fileparts(mfilename("fullpath"));
addpath(fullfile(rootSourceDir, 'neuron'));
```

**Comment by edovanveen** [comment]
Closed by pull request #42
