### ISSUE TITLE
Small documentation updates

### ISSUE THREAD

**Issue by AljenU** [mcdougallab/matlabneuroninterface#34]
Looking at the DEV_README.md, it looks like the instructions there assume that the dll has been copied to our "source" directory first. However, this should not be necessary. If, in those instructions, you replace the two instances of "source/libnrniv.dll" with the location of the libnrniv.dll within the NEURON installation folder, I expect the instructions to work just fine.

**Comment by AljenU** [comment]
When trying to run build_interface on windows, with mingw selected as both c and c++ compiler, I still got an error:

An error occurred while initializing child process:  While attempting to execute "REDACTED\matlabneuroninterface\2a03-961f-b749-17a2.exe":
CreateProcessW: Access is denied

So, we should add in the documentation, where mentioning (how to) run build_interface, that you need Administrator rights, and / or must have started Matlab as an adminstrator user, in order to be able to build the interface. Since at least clibgen.generateLibraryDefinition() needs that.

**Comment by edovanveen** [comment]
Fixed in edovanveen-phase2a_docupdates (https://github.com/edovanveen/matlabneuroninterface/tree/phase2a_docupdates).

**Comment by edovanveen** [comment]
Closed by pull request #42
