### ISSUE TITLE
Small fix for setup: also add main directory to path

### ISSUE THREAD

**Issue by AljenU** [mcdougallab/matlabneuroninterface#35]
The main directory should also be added to the matlab path, in addition to the neuron and examples subdirectories. This so matlab neuron functions are still usable when the current directory changes (for instance to go to a user's scripts directory).

Related also to #31

**Comment by edovanveen** [comment]
Fixed in edovanveen-phase2a_docupdates (https://github.com/edovanveen/matlabneuroninterface/tree/phase2a_docupdates).

**Comment by edovanveen** [comment]
Closed by pull request #42
