### ISSUE TITLE
All pure-NEURON serial simulation specification and control functions and classes available via MATLAB without Python

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#4]
For the sake of this issue, we can exclude things that depend on Python like NeuroML export or reaction-diffusion model specification.

This aim definitely includes:

Global values:

- [ ] t
- [ ] dt
- [ ] celsius
- [ ] secondorder (a flag which partly specifies integration method)

Functions:
- [ ] fadvance
- [ ] finitialize
- [ ] allsec
- [ ] continuerun
- [ ] topology (although if this could be output in a way that could be programmatically processed in addition to being displayed, that would be better)

Built-in point processes:
- [ ] IClamp
- [ ] SEClamp
- [ ] VClamp
- [ ] IClamp
- [ ] ExpSyn
- [ ] Exp2Syn
- [ ] AlphaSynapse

Artificial cells:

- [ ] PatternStim
- [ ] IntFire1
- [ ] IntFire2
- [ ] IntFire4

Classes:
- [ ] Section (in particular, this includes: getting/setting properties, getting segments, connecting to a section or segment, inserting density mechanisms, getting wholetree -- the list of all connected Sections, pt3d manipulation, psection)
- [ ] Segment (in particular including a way to access values and pointers for e.g. `seg.hh.m`, `seg.nai`, `seg.ina`; finding the section and normalized position)
- [ ] Pointer or alternative (should encapsulate information about section so e.g. don't need to pass that to a NetCon)
- [ ] NetStim
- [ ] NetCon (all networks that are built ought to be done in a way that will just work with parallel)
- [ ] Vector (in particular: recording and playing, converting to_matlab like to_python, initializing from MATLAB array)
- [ ] CVode 
- [ ] SaveState
- [ ] Random (and especially the `Random.Random123` mechanism which is essential for reproducible randomness in parallel simulations)
- [ ] LinearMechanism

Really, FInitializeHandler should be on this list, but it's so important it's #11 .

See [nrn.readthedocs.io](https://nrn.readthedocs.io) for information on these items.

**Comment by ramcdougal** [comment]
A reasonable starting point is making a handful of C/C++ functions roughly equivalent to the Python functions provided by `neuronwrapper.py` in the using-python branch.

**Comment by ramcdougal** [comment]
Usage from MATLAB should be idiomatic. e.g. call methods using dot and then the method name, not some special "call" method. (The internal side can and likely will funnel all calls to a single access point.)

**Comment by ramcdougal** [comment]
For the sake of this issue, we can exclude things that depend on Python like NeuroML export or reaction-diffusion model specification.

This aim definitely includes:

Global values:

- [ ] t
- [ ] dt
- [ ] celsius
- [ ] secondorder (a flag which partly specifies integration method)

Functions:
- [ ] fadvance
- [ ] finitialize
- [ ] allsec
- [ ] continuerun
- [ ] topology (although if this could be output in a way that could be programmatically processed in addition to being displayed, that would be better)

Built-in point processes:
- [ ] IClamp
- [ ] SEClamp
- [ ] VClamp
- [ ] IClamp
- [ ] ExpSyn
- [ ] Exp2Syn
- [ ] AlphaSynapse

Artificial cells:

- [ ] PatternStim
- [ ] IntFire1
- [ ] IntFire2
- [ ] IntFire4

Classes:
- [ ] Section (in particular, this includes: getting/setting properties, getting segments, connecting to a section or segment, inserting density mechanisms, getting wholetree -- the list of all connected Sections, pt3d manipulation, psection)
- [ ] Segment (in particular including a way to access values and pointers for e.g. `seg.hh.m`, `seg.nai`, `seg.ina`; finding the section and normalized position)
- [ ] Pointer or alternative (should encapsulate information about section so e.g. don't need to pass that to a NetCon)
- [ ] NetStim
- [ ] NetCon (all networks that are built ought to be done in a way that will just work with parallel)
- [ ] Vector (in particular: recording and playing, converting to_matlab like to_python, initializing from MATLAB array)
- [ ] CVode 
- [ ] SaveState
- [ ] Random (and especially the `Random.Random123` mechanism which is essential for reproducible randomness in parallel simulations)


Really, FInitializeHandler should be on this list, but it's so important it's #11 .

See [nrn.readthedocs.io](https://nrn.readthedocs.io) for information on these items.

**Comment by ramcdougal** [comment]
There may be better choices for defaults. For example, in today's webinar, we talked about `Vector.play` which I'd argue should default to using interpolation (but it does not).

**Comment by ramcdougal** [comment]
Note that in Python, one can create a NEURON `Vector` from a Python list via e.g.:

```python
vec = h.Vector([1, 4, 82])
```

It would be great if the same worked in MATLAB for MATLAB arrays.

**Comment by edovanveen** [comment]
Global values (eg `n.t`) - I can get/set all of these, but only `t`, `dt` tested for functionality:
* [x]  t
* [x]  dt
* [x]  celsius
* [x]  secondorder (needed to add neuron type 263-1 (int?) for this)

Functions (eg `n.fadvance()`) - I do not see `allsec`, `continuerun` show up in `clib.neuron.get_nrn_functions()`:
* [x]  fadvance
* [x]  finitialize
* [ ]  allsec
* [ ]  continuerun
* [x]  topology

Built-in point processes (eg `n.IClamp(axon, 0)`) - I can initialize all of these, but only `IClamp` tested for functionality:
* [x]  IClamp
* [x]  SEClamp
* [x]  VClamp
* [x]  ExpSyn
* [x]  Exp2Syn
* [x]  AlphaSynapse

Artificial cells (eg `n.PatternStim()`) - I can initialize all of these, but not tested for functionality:
* [x]  PatternStim
* [x]  IntFire1
* [x]  IntFire2
* [x]  IntFire4

Classes:
* [x]  Section (`n.Section("axon")`)
* [ ]  Segment (Segments are a Python thing, right?)
* [x]  Pointer or alternative (`NrnRef`, can probably use more testing)
* [x]  NetStim (`n.NetStim(0.5)` exists, not tested)
* [ ]  NetCon (exists, but have to take a better look at how to initialize this properly)
* [x]  Vector (cannot (yet) initialize from array, but can do `n.Vector(20, 0)` or `n.Vector(); n.append(1); ...`)
* [x]  CVode (`n.CVode()` exists, not tested)
* [x]  SaveState (`n.SaveState()` exists, not tested)
* [x]  Random (`r = n.Random(); r.Random123()` runs, always returns 0, more testing needed)
* [ ]  LinearMechanism (exists, but have to take a better look at how to initialize this properly)

**Comment by edovanveen** [comment]
`continuerun` does not show up in `clib.neuron.get_nrn_functions()` at all, even for datatypes that we currently not use. Is it also Python specific?

**Comment by ramcdougal** [comment]
`continuerun` is defined by the `stdrun.hoc` library. You have to call `load_file` for that first...

**Comment by edovanveen** [comment]
Ah, I understand! Sure enough, after `n.load_file("stdrun.hoc")`, now `clib.neuron.get_nrn_functions()` contains `continuerun` of type 271. Two things:
1. internally, `clib.neuron.get_nrn_functions()`  is only run on initializing a `neuron.Neuron()` instance; it needs to be rerun after `n.load_file()`
2. Indeed, the type 271 is currently not recognized

**Comment by edovanveen** [comment]
@ramcdougal What return type do neuron functions with 271 have?

**Comment by edovanveen** [comment]
Upon trying to initialize a NetCon object (see https://nrn.readthedocs.io/en/8.2.2/hoc/modelspec/programmatic/network/netcon.html#NetCon):

```
axon = n.Section("axon");
v_ref = axon.ref("v", 0.5);
n.NetCon(v_ref, 0);
```
 
Error, crashes neuron 8; not yet tried for neuron 9.

**Comment by ramcdougal** [comment]
`continuerun` is a procedure not a function. It does not return a value. See https://github.com/neuronsimulator/nrn/blob/4b26ff1352fe60e637289fab9a3e2517ad1d2f8c/share/lib/hoc/stdrun.hoc#L524

`stdrun.hoc` also defines a function called `stoppedrun`. That's returns a double. What type id did that have? (If that's also 271, we'll need to check subtypes)

**Comment by edovanveen** [comment]
`stoppedrun` has type 270. So I will add 271 as 'hoc procedures' and 270 as 'hoc functions returning a double'.

**Comment by ramcdougal** [comment]
As far as the `NetCon` goes, that's expected in that the second argument should either be a Point Process that accepts input (like an `ExpSyn`) or `None` (in Python... the HOC equivalent is an `objref` instance that doesn't have an associated object... which I'd guess is a null pointer where the object* should go). In the below, `n` and `n2` are fine, but `n3` which passes a 0 errors:

```python
>>> from neuron import h
>>> soma = h.Section(name="soma")
>>> n = h.NetCon(soma(0.5)._ref_v, None)
>>> syn = h.ExpSyn(soma(0.5))
>>> n2 = h.NetCon(soma(0.5)._ref_v, syn)
>>> n3 = h.NetCon(soma(0.5)._ref_v, 0)
NEURON: bad stack access: expecting Object**; really double 0
 near line 0
 objref hoc_obj_[2]
                   ^
        NetCon(..., 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: hocobj_call error: hoc_execerror: bad stack access: expecting Object**; really double 0
```

**Comment by edovanveen** [comment]
I see! This works:

```
axon = n.Section("axon");
v = axon.ref("v", 0.5);
es = n.ExpSyn(axon, 0.5);
nc = n.NetCon(v, es);
```

I noticed that `NetCon` is missing the attributes `delay`, `weight`, `threshold`, `x` (see `clib.neuron.get_class_methods("NetCon")` output). These are all of type 263, which is currently not recognized -- only neuron type 311 is currently recognized as object attributes. I tried adding type 263... but it caused a crash, probably because we cannot set these properties using `clib.neuron.set_pp_property`.

**Comment by ramcdougal** [comment]
That mostly makes sense. An `ExpSyn` is a point process; specifically, in your example, `es` exists at the point which is the center (0.5) of the axon. A `NetCon` connects a source to a point process, it is not itself a point process... I'll have to look into the code to figure out how to set a type 263.

**Comment by ramcdougal** [comment]
`NetCon` objects provide a steer function that can be used to get the pointers to their property names (I believe this approach will work anytime the `steer` property is non-Null):

```C++
double& steered_property(Object* obj, const char* name) {
    assert(obj->ctemplate->steer);
    auto sym2 = hoc_table_lookup(name, obj->ctemplate->symtable);
    assert(sym2);
    hoc_pushs(sym2);
    // put the pointer for the memory location on the stack 
    obj->ctemplate->steer(obj->u.this_pointer);
    return *hoc_pxpop();
}
```

For a full working example, see the **netcon-linux-nrn8** folder at https://github.com/mcdougallab/neuron-c-api-demos

That example creates a `NetStim` which generates randomly timed stimuli, and uses a `NetCon` to (1) record the stimuli times, and (2) connect the stimuli to a synaptic mechanism on a Hodgkin-Huxley cell. Once the C++ code has been run, you can visualize the results with `plot_it.py`:

![netcon](https://user-images.githubusercontent.com/6668090/230751361-53446fc5-2080-4aec-ad7a-f9ff2fd547f3.png)

**Comment by ramcdougal** [comment]
The linked example above also calls a method (`NetCon.record`) that takes an object (a `Vector`) as an argument... So maybe that'll help with the `PlorShape` constructor issue too.

**Comment by edovanveen** [comment]
New example with `NetCon` in `example_netcon.m`:

![netcon](https://user-images.githubusercontent.com/20126872/232021944-6a82fe7b-5485-435a-a642-952add2932c6.jpg)

It works, but if I run `example_netcon.m` and then `example_interactive.mlx`, MATLAB crashes (even though we use neuron 9).

**Comment by edovanveen** [comment]
I managed to initialize a LinearMechanism following the example at https://nrn.readthedocs.io/en/8.2.2/hoc/modelspec/programmatic/linmod.html#LinearMechanism:

```
% Initialization.
clear;
setup;
n = neuron.Neuron();
n.reset_sections();

% Create section.
soma = n.Section("soma");

c = n.Matrix(2, 2, 2);
g = n.Matrix(2, 2);
y = n.Vector(2);
b = n.Vector(2);
g.setval(0, 1, -1);
g.setval(1, 0, 1);
b.set(1, 10);
linmech = n.LinearMechanism(c, g, y, b, 0.5);
```

**Comment by edovanveen** [comment]
Now that Object type 263 has been added, Vector and Matrix have gained the attribute `x`, which throws an error if called directly from MATLAB (using `get_steered_property`).

**Comment by ramcdougal** [comment]
`.x` is a HOC legacy issue... it's different from the others in that it's not a scalar. Honestly I think it might be best to just not make it visible, provided that we are providing an alternative way to access a `Vector` objects values (hopefully something like `vec(2)`).

For `Vector`, `vec.x` is a 1-dimensional array (e.g. so you might say `vec.x[4]` to get the 5th element of vec)... this works in both HOC and Python, but in Python we also support the more direct syntax `vec[4]`.

For `Matrix`, `mat.x` is a 2-dimensional array. In HOC, you'd write e.g. `m.x[4][1]` for the 5th row and 2nd column.

**Comment by edovanveen** [comment]
Possible concerns (from Robert's email):

> 1. NetCon often needs a None when doing recording... I believe this is just an object with a null pointer, but I don't think this has been implemented yet in the toolbox.
> 2. If nc is a NetCon, then nc.weight is technically an array... I believe we're defaulting to setting the [0] position, which is 90% of the time all that's needed, but... (to my knowledge, there's no way of knowing how long the weight array is... usually it's just length 1).
> 3. Similarly, for VClamp, there's a .amp and a .dur that are arrays of length 3.

Number 1 should be easy to implement, but I just tested 2 and 3, and MATLAB thinks `NetCon.weight`, as well as `VClamp.amp` and `VClamp.cur` are scalars. They have the same types and subtypes as other class atributes, so we will need to add special cases for those objects.

**Comment by ramcdougal** [comment]
For 2 and 3... Internally NEURON uses this macro to test if a symbol (here `arg`) is an array; does this help?

```c
#define ISARRAY(arg) (arg->arayinfo != (Arrayinfo*) 0)
```

**Comment by ramcdougal** [comment]
With respect to 1, is there a MATLAB equivalent to `None` or `null` that we can use where Python would use `None`?

Also: one other gotcha: where Python `NetCon` objects use `delay`, in the internal stack machine you'll need `del`. The discrepancy is because `del` is a reserved keyword in Python and can't be used as a property name.

**Comment by edovanveen** [comment]
Maybe we can use MATLAB's `clib.type.nullptr`?

NEURON claims that `NetCon` does have a `delay` attribute, but `IClamp` only has a `del`.

**Comment by edovanveen** [comment]
> For 2 and 3... Internally NEURON uses this macro to test if a symbol (here `arg`) is an array; does this help?
> 
> ```c
> #define ISARRAY(arg) (arg->arayinfo != (Arrayinfo*) 0)
> ```
> 
> Edit: @nrnhines pointed out that `NetCon.weight` is a special case in NEURON's Python interface, so it'll probably have to be here too.

We can test for the following, which seems to work:

```
cppobj = vclamp.obj; 
sym = clib.neuron.hoc_table_lookup(propname, cppobj.ctemplate.symtable);
clibIsNull(sym.arayinfo);  % False for propname 'dur', true for 'i'.
```
