### ISSUE TITLE
Disable MATLAB's built-in soma function

### ISSUE THREAD

**Issue by edovanveen** [mcdougallab/matlabneuroninterface#52]
Can we disable MATLAB's built-in [soma](https://nl.mathworks.com/matlabcentral/fileexchange/26346-solutions-to-the-soma-cube?s_tid=srchtitle_soma_1) function? If a Segment is named `soma` this can lead to very strange behaviour, such as a popup window with colourful squares.

**Comment by edovanveen** [comment]
Apparently it is a MATLAB easter egg! See https://en.wikibooks.org/wiki/MATLAB_Programming/Bonus_Chapters/MATLAB_Easter_Eggs

**Comment by ramcdougal** [comment]
This is inconvenient since every (real) neuron has a soma.

**Comment by ramcdougal** [comment]
Based on @AljenU 's link, can we close this as not-a-problem since if we define something to be called a `soma`, it'll do the right thing?
