### ISSUE TITLE
PlotShape.plot is slow to load and uses inconsistent aspect ratios

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#74]
After downloading `c91662.ses` from https://modeldb.science/87284?tab=2&file=CA1_abeta/c91662.ses

Running the following takes more than 10 seconds for the plot to appear:
```matlab
n = neuron.Neuron();
n.load_file("c91662.ses");
ps = n.PlotShape(0);
ps.plot();
```

Tested on a Chromebook with 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz with
```
$ uname -a
Linux penguin 5.15.108-18910-gab0e1cb584e1 #1 SMP PREEMPT Sat Jun 3 18:21:02 PDT 2023 x86_64 GNU/Linux
```

![image](https://github.com/mcdougallab/matlabneuroninterface/assets/6668090/30fe5db8-c1bf-41e4-b8e8-fc523956a92d)

![image](https://github.com/mcdougallab/matlabneuroninterface/assets/6668090/04fd076f-b927-4bf4-a875-c66da3de308a)

**Comment by vijayiyer05** [comment]
@AljenU You could assign this issue to me, to indicate a pending action to seek some input from my employer. Looks like I need to be added to the repo as a collaborator.

**Comment by hvangeffen** [comment]
@ramcdougal could you send a screenshot of the matlab profiler when running this?

Can be run by clicking:
![image](https://github.com/mcdougallab/matlabneuroninterface/assets/144685504/2db297e4-15e2-4936-8527-1a6be1c5c5d6)

And then filling in the function name / .m file name in the profiler window:
![image](https://github.com/mcdougallab/matlabneuroninterface/assets/144685504/41212283-a701-47d2-a100-f14e095d9f1c)

An example of what I get is this:
![image](https://github.com/mcdougallab/matlabneuroninterface/assets/144685504/9dfe84db-c511-4317-ba98-f0054d95c613)

**Comment by AljenU** [comment]
> @ramcdougal could you send a screenshot of the matlab profiler when running this?
> 


FYI, Matlab command window alternative:

```
profile on
example_c91662_plot
profile viewer
```

or on one line

`profile on; example_c91662_plot; profile viewer`

**Comment by hvangeffen** [comment]
> Here's what I see... you'll notice that the self time for `PlotShape.plot` (which is mostly in the plotting) is less than 2 seconds, but the total time is almost 37 seconds... most of which is in working with structs in `get_pt3d`...
> 
> ![image](https://private-user-images.githubusercontent.com/6668090/285961119-62dae73e-375a-474f-b324-332f044217f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjAyNzYsIm5iZiI6MTcwMTE1OTk3NiwicGF0aCI6Ii82NjY4MDkwLzI4NTk2MTExOS02MmRhZTczZS0zNzVhLTQ3NGYtYjMyNC0zMzJmMDQ0MjE3ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDgyNjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ4MjhjZjg0ZTAxMmVhYmQxZjhkNTg0YmIyMjQ4NDk1NTY1MGJiNzZhOGNiMzE4ZDIyZmJjNWFkOTQ3Mzk4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cvHzhk73-8VOmKkC9KZkpofeze8RChkeniNLal-EARQ)
> 
> Clicking in to the problematic function, we see:
> 
> ![image](https://private-user-images.githubusercontent.com/6668090/285961456-8db3a8eb-5732-447d-a50c-3ea0df020530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjAyNzYsIm5iZiI6MTcwMTE1OTk3NiwicGF0aCI6Ii82NjY4MDkwLzI4NTk2MTQ1Ni04ZGIzYThlYi01NzMyLTQ0N2QtYTUwYy0zZWEwZGYwMjA1MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDgyNjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU2Y2UwNDg0NmE0MWJjMjY1MjZmYzY2NmVlNzYwMGYwZWJjZjQ1NDVlYThkMzEyNWJhN2RjODY1NjY5NzBlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4ApQGhF8FCoRUv4dUamqSIlVEDA6osR0EM_XAWuyxE8)
> 
> ![image](https://private-user-images.githubusercontent.com/6668090/285961547-6f298606-3ba1-4e31-ac51-4fd9bc424e90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjAyNzYsIm5iZiI6MTcwMTE1OTk3NiwicGF0aCI6Ii82NjY4MDkwLzI4NTk2MTU0Ny02ZjI5ODYwNi0zYmExLTRlMzEtYWM1MS00ZmQ5YmM0MjRlOTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDgyNjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNiZGU1ZmRhNmJhZGE0ZTEzMGJjZWU4ZDdlZmM3NDU5Zjk5Nzg1MzFiODIzN2Y1ZjZiZGUyNDA5ZWU4MjM5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K23NuCJatMCrYCglgRr4mMdtd3OIOtLBAyKnXQkDHEE)
> 
> and here is `get_nseg` which isn't as bad, but is certainly not something we should be spending 2 seconds on:
> 
> ![image](https://private-user-images.githubusercontent.com/6668090/285962082-34183823-ade0-4878-a51c-01073f4be7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjAyNzYsIm5iZiI6MTcwMTE1OTk3NiwicGF0aCI6Ii82NjY4MDkwLzI4NTk2MjA4Mi0zNDE4MzgyMy1hZGUwLTQ4NzgtYTUxYy0wMTA3M2Y0YmU3ZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDgyNjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZhM2QxN2FlMjU1NjUwNjJhZTk4M2Y4ZTg1N2Q3ZGIwZDEyNTg0NmI1MTc2OGMzMjYwNTlhNjE0NzQ4NTA0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.R71xbyd5GZXNmvYDj1EYxhME_H-eUxpgd7XURK2WF3o)
> 
> ![image](https://private-user-images.githubusercontent.com/6668090/285962191-ce4b3200-c204-46ca-95bc-cdc4a928845a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjAyNzYsIm5iZiI6MTcwMTE1OTk3NiwicGF0aCI6Ii82NjY4MDkwLzI4NTk2MjE5MS1jZTRiMzIwMC1jMjA0LTQ2Y2EtOTViYy1jZGM0YTkyODg0NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDgyNjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNlMzJiMWVhNDU1OGFlODI5MjliOGM4NjEwZDNhZGYzY2UxMTA1ZDdjNGY5MzhiOTM5YTFlNDMxMjY0NTEyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RVopsBlP_z3iv1ifILQECtX6IMSAH_66vCsjOYAhYzw)

Thank you for the detailed breakdown. This helps a lot.

**Comment by hvangeffen** [comment]
@vijayiyer05 Issue is being worked on in branch [74-plotshapeplot-is-slow-to-load-and-uses-inconsistent-aspect-ratios](https://github.com/mcdougallab/matlabneuroninterface/tree/74-plotshapeplot-is-slow-to-load-and-uses-inconsistent-aspect-ratios).
Can also be seen for each issue in the sidebar at the top:
![image](https://github.com/mcdougallab/matlabneuroninterface/assets/144685504/f184668f-fcc3-4de4-9eb1-b19a640f58d7)

**Comment by vijayiyer05** [comment]
Thank you @hvangeffen for adding this note, and for teaching me about this (subtle!) part of the issue sidebar.

**Comment by edovanveen** [comment]
Status:

* Ready for review
