### ISSUE TITLE
rendering of equations in livescripts

### ISSUE THREAD

**Issue by AljenU** [mcdougallab/matlabneuroninterface#82]
For me, on my Linux machine, the equations in example_temperature.mlx do not render correctly. Instead, I get

![image](https://github.com/mcdougallab/matlabneuroninterface/assets/74405789/d7d8d747-fefd-4ac6-a57e-80051951a15d)

Might be local to my current computer, does need further investigation.

**Comment by tkuenzmw** [comment]
Hi Aljen,
The equations render on my linux machine (23a, both classical and new desktop). When you click on the question marks, does the equation tab in the toolbar appear?
Thomas

From: AljenU ***@***.***>
Sent: Tuesday, 11 July 2023 15:28
To: mcdougallab/matlabneuroninterface ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mcdougallab/matlabneuroninterface] rendering of equations in livescripts (Issue #82)


For me, on my Linux machine, the equations in example_temperature.mlx do not render correctly. Instead, I get

[image]<https://user-images.githubusercontent.com/74405789/252677953-d7d8d747-fefd-4ac6-a57e-80051951a15d.png>

Might be local to my current computer, does need further investigation.

**Comment by AljenU** [comment]
Not sure what was happening, when I currently look at example_temperature.mlx on a Linux machine and 2023b the equations show correctly. Since this is no longer reproducible, I'll close this issue.
