### ISSUE TITLE
Command-line interface (CLI) usability enhancements

### ISSUE THREAD

**Issue by vijayiyer05** [mcdougallab/matlabneuroninterface#84]
Umbrella issue for exploring/tracking/dispensing ideas to enhance the consistency & usability of the NEURON Toolbox command-line interface (CLI)

**Comment by vijayiyer05** [comment]
- [ ] Rename `neuron.Neuron` to 'neuron.Session` to better convey class meaning (and to avoid stuttering)

**Comment by ramcdougal** [comment]
WRT `neuron.Session`, my only hesitation is that it might imply you could have more than one NEURON session, which you can't do at this point.

**Comment by vijayiyer05** [comment]
> WRT neuron.Session, my only hesitation is that it might imply you could have more than one NEURON session, which you can't do at this point.

Given this limitation, I would suggest to use the [Singleton pattern](https://www.mathworks.com/matlabcentral/fileexchange/24911-design-pattern-singleton-creational) for the class. In short: make constructor private & make a static method with a persistent variable.

**Comment by edovanveen** [comment]
- [ ] Rename `neuron.Neuron` to `neuron.Session` & consider Singleton pattern
- [ ] Rethink `NrnRef` class: add MatLab wrapper object for direct value assignment and retrieval
- [ ] Adhere to naming conventions as much as possible (not possible for dynamic methods/properties)

**Comment by vijayiyer05** [comment]
Re naming conventions, a few patterns can be seen from averaging across various classes implemented in MathWorks products:

- lowercase package names
- UpperCamelCase class names
- UpperCamelCase property names
- lowerCamelCase method names (except for constructors, which match the class name)
- lowerCamelCase function names

**Comment by vijayiyer05** [comment]
Worth taking a look at the 'new' subsref: https://www.mathworks.com/help/matlab/ref/matlab.mixin.indexing.redefinesdot-class.html

Suggest to try it for 1-2 of the classes, if it's straightforward

**Comment by hvangeffen** [comment]
Could also take a look at https://nl.mathworks.com/help/matlab/ref/libpointer.html and related pages of matlab working with c to see how they define their interfaces

**Comment by vijayiyer05** [comment]
> * [ ]  Rename `neuron.Neuron` to `neuron.Session` & add separate function to start a session

For the separate function, how about keeping it simple such as `neuron.launch`. Given it's a singleton, I don't think there's a need to put 'Session' in the function name.

**Comment by vijayiyer05** [comment]
> > * [ ]   Rename `neuron.Neuron` to `neuron.Session` & add separate function to start a session
> 
> For the separate function, how about keeping it simple such as `neuron.launch`. Given it's a singleton, I don't think there's a need to put 'Session' in the function name.

Looking back at this, I should clarify: main thought was that I don't think it's a golden rule to use 'session' in the `Session` object factory method name even though that's the name of the object returned. 'Launch' came to mind first but that's not the main point.

**Comment by ramcdougal** [comment]
I'm still confused by the rationale for this. It's going to be a someone for the foreseeable future. What's the advantage of returning a Singleton that requires a separate initialization step as opposed to just returning it initialized? Splitting it in two just seems like extra work.

**Comment by vijayiyer05** [comment]
> I'm still confused by the rationale for this. It's going to be a someone for the foreseeable future. What's the advantage of returning a Singleton that requires a separate initialization step as opposed to just returning it initialized? Splitting it in two just seems like extra work.

I agree the constructor can 'know' that it's a singleton & just initialize itself if sensible (as it is here). No need for a separate initializer function. But that doesn't address the multiple constructor call matter. Note the constructor is typically hidden from the user in the singleton pattern, i.e., there's only one function to know.  

Personally I wish there were a way to implement a Singleton constraint without a separate factory method. But currently a MATLAB constructor has no way to enforce that it's the only one. 

That said, can you remind me if NEURON itself implements a singleton constraint? If only one NEURON session is possible under the hood, it's likely possible to avoid re-implementing a singleton constraint in the MATLAB wrapper.

**Comment by edovanveen** [comment]
@ramcdougal ready for review/merge

**Comment by vijayiyer05** [comment]
@edovanveen, great that you've made progress on the command chaining. Is there a particular script file you can point me to where some syntax was improved or made possible by this improved command chaining?

**Comment by edovanveen** [comment]
@vijayiyer05 Ah it seems that I misunderstood your question. An example of syntax that is possible now is:

```
>> n = neuron.launch();
>>v = n.Vector().append(1).append(2);
>>disp(double(v));
     1     2
```

**Comment by ramcdougal** [comment]
It's of course never literally *necessary*. However, sometimes it is convenient to allow things that one might conceptualize as single concepts to be expressed in a single statement.

(I would argue that multiple statements on one line don't convey the same conceptual relatedness that one single statement conveys.)

The classic example that people use all the time in Python is to create a `Vector` and tell it to record some thing:
```python
v = h.Vector().record(soma(0.5)._ref_t)
```

When you invoke a method on an object you don't necessarily return a modified version of an object; you may return a new object.

Being used to other programming languages, I don't understand why it would never not be allowed. Whether or not it should be used in a specific context is a different question.

**Comment by vijayiyer05** [comment]
Thanks @ramcdougal for your thoughts on this. Sorry I didn't catch it sooner. 

Interesting re the importance you see of chaining for conceptual relatedness.  

When you say methods can either return a modified version or a new object, can you comment on what's more typical in Python in your experience? On the MATLAB side, yes both could be true, but it's always one or the other for a given class, i.e., a class is either a handle class or a value class. 

I haven't fully internalized the general case of dot notation to answer your broader puzzle, but what comes to mind is that a method (or property access) by dot notation could return a non-object structure or an object of a different type. So my instinct is that chaining would only work in some circumstances. 

Still interested to hear thoughts from @edovanveen on this. Again, thanks for weighing in!

**Comment by edovanveen** [comment]
@vijayiyer05 All supported Neuron functions (for now, at least) can only return a string, a double, or another Neuron object. So as long as all matlab wrappers support chained method calls, there should not be an issue.

**Comment by ramcdougal** [comment]
The return type shouldn't matter unless this is a `subsref` limitation. That which comes after the dot acts on whatever object the previous item returned.

In Python, the `PlotShape.plot` method returns an instance of a plotly or matplotlib graph, and so anything that's dotted on to that would have to be an e.g. plotly graph method not a PlotShape method.

**Comment by edovanveen** [comment]
@ramcdougal in this case, subsref-chaining does not work on classes without a subsref implementation... Because dynamic methods don't actually exist in matlab.

**Comment by vijayiyer05** [comment]
Great discussion, thank you both!
