### ISSUE TITLE
Support calling and being called by Python and HOC functions, etc

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/matlabneuroninterface#9]

**Comment by ramcdougal** [comment]
The core idea here is that we want HOC/Python to be able to call MATLAB routines... there are also a number of functions (e.g. FInitializeHandler see #11) that can invoke callbacks, and we'd like to be able to have those call NEURON as well.

A way to make this work: we can define a paring between a name and a C function pointer in the NEURON stack machine. This would add entries into the NEURON name space, but it would be mostly fine if they had some elaborate autogenerated name, say `neuron_toolbox_5243_64AE_5424` where the last bit is some kind of UUID.

Once they're known to the stack machine, they can be called by HOC. 

For a working example, see https://github.com/mcdougallab/neuron-c-api-demos/blob/main/function-callbacks-nrn9/function-callbacks.cpp

The key parts are:

```C++
void test_callback(void) {
    cout << "Hello from C++" << endl;
    // must call hoc_ret... to tell the stack we're returning a value
    hoc_ret();
    // return value must be pushed onto the stack
    hoc_pushx(42);
}

...

    hoc_oc("{value=test_callback()}");
    hoc_oc("print \"received value: \", value");
```

If it turns out that we couldn't generate a new C++ function pointer for each MATLAB function we'd like to call, we could have one access point (say a function called `neuron_toolbox_interface`) that takes a parameter indicating which function is to be called (and possibly other parameters for the other functions... )

**Comment by edovanveen** [comment]
To do:

* hoc install `nrnmatlab`
* nrnmatlab mex evals a matlab function
* return 0 or 1

We want to be able to run in HOC: `nrnmatlab("matlab code")`. This just returns 0 or 1; there is no obvious way to get return values back from matlab.

Try on linux with no-desktop version to run in process.
